### ISSUE TITLE
Checking potencial problem in function F_update.m, relates to #101

### ISSUE THREAD

**Issue by rodralez** [rodralez/NaveGo#107]
F_update.m
    The state transition matrix in the program is 15 by 15, which is different from the original paper,this in itself has nothing to say.

In the program：
F = [F11 F12 F13 DCMbn Z ;
F21 F22 F23 Z -DCMbn ;
F31 F32 F33 Z Z ;
Z Z Z Fgg Z ;
Z Z Z Z Faa ;
];

G = [DCMbn Z Z Z ;
Z -DCMbn Z Z ;
Z Z Z Z ;
Z Z Fbg Z ;
Z Z Z Fba ;
];

why not:

F = [F11 F12 F13 -DCMbn Z ;
F21 F22 F23 Z DCMbn ;
F31 F32 F33 Z Z ;
Z Z Z Fgg Z ;
Z Z Z Z Faa ;
];

G = [-DCMbn Z Z Z ;
Z DCMbn Z Z ;
Z Z Z Z ;
Z Z Fbg Z ;
Z Z Z Fba ;
];

Only in this way it is reasonable. Is there any special treatment or transformation?
It is also the latter rather than the former in corresponding paper about NaveGo.

**Comment by rodralez** [comment]
This is an outdated version of the function. Please, check the last version.

**Comment by scott198510** [comment]
@rodralez  The last version is : 

F = [F11 F12 F13 DCMbn Z ;
F21 F22 F23 Z DCMbn ;
F31 F32 F33 Z Z ;
Z Z Z Fgg Z ;
Z Z Z Z Faa ;
];

G = [DCMbn Z Z Z ;
Z DCMbn Z Z ;
Z Z Z Z ;
Z Z Fbg Z ;
Z Z Z Fba ;
];


This is  not right,  no minus sign in the last verison.

The right one is :  

F = [F11 F12 F13 -DCMbn Z ;
F21 F22 F23 Z DCMbn ;
F31 F32 F33 Z Z ;
Z Z Z Fgg Z ;
Z Z Z Z Faa ;
];

G = [-DCMbn Z Z Z ;
Z DCMbn Z Z ;
Z Z Z Z ;
Z Z Fbg Z ;
Z Z Z Fba ;
];

**Comment by rodralez** [comment]
I had to add again a negative sing to the 2do DCMbn in matrices F and G because MPU-6000 example stopped working. If you try this example with your proposed matrices F and G, the INS/GNSS diverges badly.

**Comment by scott198510** [comment]
@rodralez  Can you tell me some  explanations?

I have refered to the books,

![image](https://user-images.githubusercontent.com/17826746/157175211-a2da682b-6ae3-4379-a8f0-0554dc94dcc4.png)

**Comment by rodralez** [comment]
In this case, Farrellś model shows to be working. You may compare both models, Farrell's and Groves', and thus determine what's going on.

**Comment by scott198510** [comment]
@paolozoccarato   If you try this example with your proposed matrices F and G, the INS/GNSS diverges badly.

I have used the model as my proposed matrices, the result is a little different, but it doesn't diverge.
