### ISSUE TITLE
Is choosing eps reasonable？

### ISSUE THREAD

**Issue by scott198510** [rodralez/NaveGo#123]
ekinox_gnss.eps = mean(diff(mpu6000_imu.t)) / 2; %  A rule of thumb for choosing eps.

In old code, ekinox_gnss.eps = 0.0025

In new codes, ekinox_gnss.eps =0.002

But in my opinion，ekinox_gnss.eps = 0.6 *mean(diff(mpu6000_imu.t)) is best,  set multiplier to  0.5, that is not reasonable
The multiplier should be a little larger than 0.5.

You can compare the first index `gdx` in  ins_gnss, that is different.
@rodralez

**Comment by rodralez** [comment]
If you set,

`ekinox_gnss.eps = 0.6 *mean(diff(mpu6000_imu.t)) `

the `eps` time window is too big and NaveGo executes the same epoch twice, which is an increase in computation time. Please, uncomment line 321 in function `ins_gnss` and check.

Kind regards.

![image](https://user-images.githubusercontent.com/5432060/163694142-a9f8db6f-a4bc-4c59-9c1e-399cbeb8e025.png)
