### ISSUE TITLE
how to generate trajectory data?

### ISSUE THREAD

**Issue by huazai665** [rodralez/NaveGo#15]
Dear Rodrigo,
thanks for this useful toolbox!
I would like to ask a question how to generate trajectory data? 
I have some real data collected by apm or pixhawk, how to use amp or pixhawk data to your model?

**Comment by rodralez** [comment]
Hi huaza665,

Sorry for the late reply.

In general, you have to extract the IMU and GNSS data from the logs of any autopilot, and put these data in NaveGo format.

You also need the error profile from each sensor and again, to input these data in NaveGo format.

Regards.
