### ISSUE TITLE
Strange accuracy problem whereas RTK received

### ISSUE THREAD

**Issue by brumann** [rodralez/NaveGo#17]
Dear Rodrigo, 

First of all thank you for your code, it is very helpful. 

However I noticed a strange phenomenon, at the beginning of my simulation the hybridization is actually worse than GPS alone. For almost 3min there is about 35cm of error for the hybride trajectory whereas GPS error is below 2cm. Imu data are generated from the reference trajectory, with error estimated in static with Allan-variance. 

What I do not understand is that since GPS.stdm is of about 1cm for this period, the kalman filter should give more weight to GNSS, and it appears not to be the case ? I have spent days on it, I don't see what I am missing. 
I tried to take only gnss when RTK is received, with no success (kalman filter diverge).
Screenshots are attached. 

Thank you in advance for your answer
Sincerely,

![image](https://user-images.githubusercontent.com/42934775/45734829-29070c00-bbe6-11e8-9fa0-f5f4735e7622.png)

![image](https://user-images.githubusercontent.com/42934775/45734818-22789480-bbe6-11e8-91f6-4febc5317252.png)
(The vehicle starts moving after 15sec)

**Comment by LZNUDT** [comment]
in my opinion ,the outcome of the integration of INS/GNSS  is worse than RTK at the begining! so you may check your INS algrithm and Kalman Fusion Equation!

**Comment by rodralez** [comment]
Dear brumann,

I think you should tune the values of Q and R matrices. Errors in KF tend
to be very sensitive to the values of these matrices.

Regards.
-- 
Rodrigo Gonzalez
