### ISSUE TITLE
llh2ecef.m

### ISSUE THREAD

**Issue by AleksKnezevic** [rodralez/NaveGo#18]
It seems that llh2ecef.m, referenced in ned2ecef.m is missing.

**Comment by rodralez** [comment]
El mié., 16 ene. 2019 a las 11:08, AleksKnezevic
(<notifications@github.com>) escribió:

> It seems that llh2ecef.m, referenced in ned2ecef.m is missing.

Dear Aleks,

Thank you for using NaveGo and for spotting this error.

I have upload the llh2ecef.m function to NaveGo's repository.

Regards.
-- 
Rodrigo Gonzalez

**Comment by AleksKnezevic** [comment]
Thanks for the quick response!
