### ISSUE TITLE
sgolayfilt warning

### ISSUE THREAD

**Issue by kmos** [rodralez/NaveGo#2]
In a normal execution of navego_example.m, I receive a warning in gyro_gen:

`Warning:` Matrix is close to singular or badly scaled. Results may be inaccurate. RCOND =  5.892434e-33. 
> In sgolay (line 101)
  In sgolayfilt (line 71)
  In gyro_gen (line `43)`

is it normal?

**Comment by rodralez** [comment]
Dear kmos,

Thank you very much for pointing out this issue.

According to me, this is not an error but it is not an elegant solution neither.

I adjusted both parameters in sgolayfilt(),  the polynomial order K and the frame size F to avoid this warning. 

Regards.
