### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by sume-cn** [rodralez/NaveGo#22]
https://github.com/rodralez/NaveGo/blob/c3be322c1dad2377258ab901a5ae8e61c22cad4b/ins_gnss.m#L12

vrw: 1x3 angle velocity walks (m/s^2/root-Hz).
↓
vrw: 1x3 velocity random walks (m/s^2/root-Hz).

**Comment by rodralez** [comment]
Hi, thank you very much for pointing out this typo. It was already corrected. Kind regards.
