### ISSUE TITLE
vel_update

### ISSUE THREAD

**Issue by Barak28** [rodralez/NaveGo#23]
Hi,
Please note that vel_update corrects the specific force by subtracting g as a vector (31) and not by a scalar as written in function description (moreover, fn_c dimensions are (31)..so g must be (3*1) )
Thanks!

**Comment by rodralez** [comment]
Hi Barak,

Thank you for using NaveGo!

Yes, g is a 3x1 vector, so the header of vel_update() was wrong. Thank you for pointing out this error. It is already corrected.

Kind regards.
