### ISSUE TITLE
F_update (lines 81-112)

### ISSUE THREAD

**Issue by Barak28** [rodralez/NaveGo#24]
Hi,
In F_update (lines 81-112):
Updating F matrix for the misalignment errors doesn't match Farrell's book (up to minus sign). Please see page 394 (CHAPTER 11. AIDED INERTIAL NAVIGATION). 

What is the right implementation ? 

Thanks,
Barak

**Comment by rodralez** [comment]
El lun., 22 jun. 2020 a las 18:08, Barak Or
(<notifications@github.com>) escribió:
>
> Hi,
> In F_update (lines 81-112):
> Updating F matrix for the misalignment errors doesn't match Farrell's book (up to minus sign). Please see page 394 (CHAPTER 11. AIDED INERTIAL NAVIGATION).
>
> What is the right implementation ?

Hi Barak,

Matrix F is taken from Titterton's book, Eq. 12.18, p. 345.

Matrix G is taken from Farrell's book, Eq. 11.108, p. 407.

Now this is stated in the header of the function file.

Kind regards.
