### ISSUE TITLE
关于数据的说明

### ISSUE THREAD

**Issue by kakusang2020** [rodralez/NaveGo#26]

**Comment by rodralez** [comment]
> Can you write a note about the use of the data? I want to try it with the
instrument data of my laboratory. I don’t know how to use it. I can’t find
you on WeChat. I look forward to your reply, thank you!

Hello,

You have to provide IMU and GPS data to NaveGo as two different data
structures. The examples within the examples folder will help to understand
these two data structures.

Kind regards.

PS: sorry, I don't read or speak Chinese.

**Comment by rodralez** [comment]
This is not an issue, just a question from a NaveGo user.
