### ISSUE TITLE
About the "eps"

### ISSUE THREAD

**Issue by kakusang2020** [rodralez/NaveGo#27]
Would you mind telling me about how to calculate the 
eps(time interval to compare current IMU time to current GNSS time vector (s).)

Usually, how can I get it?

**Comment by rodralez** [comment]
El vie., 28 ago. 2020 a las 2:44, (<notifications@github.com>) escribió:

> Would you mind telling me about how to calculate the
> eps(time interval to compare current IMU time to current GNSS time vector (s).)
>
> Usually, how can I get it?

Hello kakusang2020,

A rule of thumb for choosing eps is,

gnss.eps = mean ( diff ( imu.t ) ) / 2;

Kind regards.

-- 
Rodrigo Gonzalez

**Comment by kakusang2020** [comment]
Thanks for your reply! Sorry, I have another question, about the " LOAD REF DATA", I need to use Inertial Explorer, so can you tell me about how to use my imu raw data convert to .imr data?
