### ISSUE TITLE
size of F and G matrix

### ISSUE THREAD

**Issue by AliRamshini** [rodralez/NaveGo#35]
Hi, Dr Gonzalez 
After I study your codes , figure out in your article , dimension of F matrix is 21*21 but you programmed it 15*15 , why? 
and please submit  a reference for more understanding a ZUPT algorithm and formula .
thank you .

**Comment by rodralez** [comment]
Hi Ali,

Static bias can be modeled as a sum of a deterministic part and a stochastic part. The deterministic static bias can be found using a calibration method in a laboratory. The stochastic static bias provides a constant variation in the bias every time the IMU is switched on (run-to-run variation). This error ca be compensated by the Kalman filter.

Previous versions of NaveGo compensated the stochastic static biases but we realized that this error was also captured by the stochastic dynamic biases, so the compensation of stochastic static biases was dropped and the state vector was reduced from 21 states to 15 states.

Kind regards.
