### ISSUE TITLE
Kalman filter

### ISSUE THREAD

**Issue by yangming19940101** [rodralez/NaveGo#46]
I have read your paper,Nave GO : a simulation framework for low -cost integrated navigation systems. I have a question? formulation:(23.a) have matrix G and matrix U, but In your matlab simulation code,I don't see G and U.  
In Kf_prediction.m , kf.xi = kf.A *kf.xp.  so I am very confused about this question? please help me understand it. 

Thank you for your attention ...

**Comment by rodralez** [comment]
> I have read your paper,Nave GO : a simulation framework for low -cost integrated navigation systems. I have a question? formulation:(23.a) have matrix G and matrix U, but In your matlab simulation code,I don't see G and U.
> In Kf_prediction.m , kf.xi = kf.A *kf.xp. so I am very confused about this question? please help me understand it.

Hello, matrices G and F (not U) must be updated before the execution of the Kalman filter. These two matrices are updated in the F_update() function. 

Kind regards.

**Comment by 4nDrEi95** [comment]
@rodralez F_update() function is missing from the package.

**Comment by rodralez** [comment]
> @rodralez F_update() function is missing from the package.

Thank you for pointing out this error. This problem was already solved.
