### ISSUE TITLE
Questions about the new dt term in F_update

### ISSUE THREAD

**Issue by yifaan** [rodralez/NaveGo#5]
Hi Rodrigo,

I noticed you add dt in the F matrix. I don't really understand this, can you explain why do you need to multiply the fixed bias term with dt here?

F= [Fee  Fev  Fep   (DCMbn)*dt  Z       (DCMbn)   Z;
    Fve  Fvv  Fvp   Z       (-DCMbn)*dt   Z       (-DCMbn);
    Fpe  Fpv  Fpp   Z        Z             Z    Z;
    Z    Z    Z     Z        Z             Z    Z;
    Z    Z    Z     Z        Z             Z    Z;
    Z    Z    Z     Z        Z             Fgg  Z;
    Z    Z    Z     Z        Z             Z    Faa;
    ];

Regards

**Comment by rodralez** [comment]
Dear Yifaan,

I have read this implementation of F matrix in some paper, but I cannot remember where.

It seems that I tested this modification in F, but forgot to deleted.

The modified F seems to work well in NaveGo, but I will keep the original version, which is supported by several books in the Navigation field.

Regards.
