### ISSUE TITLE
Function for generating ref.mat

### ISSUE THREAD

**Issue by paolozoccarato** [rodralez/NaveGo#7]
Dear Rodrigo,
many thanks for this useful toolbox!

Would it be possible to add also the function for generating the ref.mat data or are you using an external tool for generating it?

Many thanks.

Best Regards.
Paolo

**Comment by rodralez** [comment]
Dear Paolo,

Thanks for your comments!

Yes, I used an external tool for the NaveGo example which is not open source. Someone commented me that the following tool is an open trajectory generator: http://www.instk.org/. Please, check it.

Regards.

**Comment by huazai665** [comment]
can you supply the exteral tool for trajectory generator?

**Comment by rodralez** [comment]
El sáb., 18 ago. 2018 a las 8:32, huazai665
(<notifications@github.com>) escribió:

> can you supply the exteral tool for trajectory generator?

Hello,

No, I cannot. The trajectory generator is copyright software.

Regards.
-- 
Rodrigo Gonzalez

**Comment by huazai665** [comment]
can you tell me the trajectory generator software name? I buy it

**Comment by rodralez** [comment]
El dom., 19 ago. 2018 a las 11:13, huazai665
(<notifications@github.com>) escribió:

> can you tell me the trajectory generator software name? I buy it

I don't know if this tool is still available for buying.

Please, contact me at rodralez [at] frm [dot] utn [dot] edu [dot] ar,
and we can keep talking about this.

Regards.
-- 
Rodrigo Gonzalez

**Comment by huazai665** [comment]
can you share us some trajectory data?
